// <auto-generated />
using MessageBoardAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MessageBoardAPI.Migrations
{
    [DbContext(typeof(MessageBoardAPIContext))]
    [Migration("20200402172655_seed1")]
    partial class seed1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MessageBoardAPI.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Topic");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 7,
                            Topic = "Surviving COVID"
                        },
                        new
                        {
                            GroupId = 8,
                            Topic = "Cooking during COVID"
                        },
                        new
                        {
                            GroupId = 9,
                            Topic = "Gaming during COVID"
                        });
                });

            modelBuilder.Entity("MessageBoardAPI.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("GroupId");

                    b.HasKey("MessageId");

                    b.HasIndex("GroupId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            Description = "How to stash water and fuel",
                            GroupId = 7
                        },
                        new
                        {
                            MessageId = 2,
                            Description = "How to cook the squirrel that died in your backyard",
                            GroupId = 8
                        },
                        new
                        {
                            MessageId = 3,
                            Description = "How to cheat at a puzzle",
                            GroupId = 9
                        });
                });

            modelBuilder.Entity("MessageBoardAPI.Models.Message", b =>
                {
                    b.HasOne("MessageBoardAPI.Models.Group", "Group")
                        .WithMany("Messages")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
